name: grim_receiver_grid
description: GRIM receiver grid screen (internal package).
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  grim_core:
    path: ../grim_core
  grim_image_full_screen:
    path: ../grim_image_full_screen
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
