name: grim_role_select
description: GRIM role select screen (internal package).
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  grim_core:
    path: ../grim_core
  grim_receiver_grid:
    path: ../grim_receiver_grid
  grim_sender_camera:
    path: ../grim_sender_camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
